Areas/Admin/Controllers/CategoriesAdminController.cs
using HaVanThy_DoAn_WebDoTheThaoNike.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HaVanThy_DoAn_WebDoTheThaoNike.Models;
//using HaVanThy_DoAn_WebDoTheThaoNike.Filters;
using System.Data.Entity;

namespace HaVanThy_DoAn_WebDoTheThaoNike.Areas.Admin.Controllers
{
    [AdminAuthorization]
    public class CategoriesAdminController : Controller
    {
        // GET: Admin/CategoriesAdmin
        NikeDBContext db = new NikeDBContext();
        public ActionResult Index()
        {
            List<Category> categories = db.Categories.ToList();
            return View(categories);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                var existingCategory = db.Categories.FirstOrDefault(c => c.CategoryName.Equals(category.CategoryName, StringComparison.OrdinalIgnoreCase));
                if (existingCategory != null)
                {
                    ModelState.AddModelError("CategoryName", "A category with this name already exists.");
                    return View(category);
                }

                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Edit(int id)
        {
            var category = db.Categories.FirstOrDefault(c => c.CategoryID == id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                var existingCategory = db.Categories.FirstOrDefault(c => c.CategoryName.Equals(category.CategoryName, StringComparison.OrdinalIgnoreCase) && c.CategoryID != category.CategoryID);
                if (existingCategory != null)
                {
                    ModelState.AddModelError("CategoryName", "Another category with this name already exists.");
                    return View(category);
                }

                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Delete(int id)
        {
            var category = db.Categories.FirstOrDefault(c => c.CategoryID == id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var category = db.Categories.FirstOrDefault(c => c.CategoryID == id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Areas/Admin/Views/CategoriesAdmin/Create.cshtml
@model HaVanThy_DoAn_WebDoTheThaoNike.Models.Category

@{
    ViewBag.Title = "Create Category";
}

<main class="mt-4">
    <div class="container-fluid px-4">
        <div class="card">
            <div class="card-body row">
                <div class="col-md-2">
                </div>
                <div class="col-md-8">
                    @using (Html.BeginForm("Create", "CategoriesAdmin", FormMethod.Post, new { @class = "row g-3" }))
                    {
                        <fieldset>
                            <h2 class="mb-4">ADD NEW CATEGORY</h2>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <!-- Category Name -->
                            <div class="col-lg-12 col-md-12">
                                @Html.LabelFor(model => model.CategoryName, new { @class = "form-label" })
                                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", placeholder = "Category Name" } })
                                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                            </div>
                        </fieldset>

                        @Html.ValidationSummary()

                        <div class="col-12 mt-3">
                            <button type="submit" class="btn btn-primary">Create</button>
                            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
                        </div>
                    }
                </div>
                <div class="col-md-2">
                </div>
            </div>
        </div>
    </div>
</main>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>

Areas/Admin/Views/CategoriesAdmin/Delete.cshtml
@model HaVanThy_DoAn_WebDoTheThaoNike.Models.Category

@{
    ViewBag.Title = "Delete Category";
}


<main class="mt-4">
    <div class="container-fluid px-4">
        <div class="card">
            <div class="card-body">
                <h2>DELETE CATEGORY</h2>
                <p>Are you sure you want to delete this category?</p>

                @using (Html.BeginForm("Delete", "CategoriesAdmin", new { id = Model.CategoryID }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <table class="table">
                        <tr>
                            <th>Category Name</th>
                            <td>@Model.CategoryName</td>
                        </tr>
                    </table>

                    <button type="submit" class="btn btn-danger">Delete</button>
                    @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
                }
            </div>
        </div>
    </div>
</main>

Areas/Admin/Views/CategoriesAdmin/Edit.cshtml
@model HaVanThy_DoAn_WebDoTheThaoNike.Models.Category

@{
    ViewBag.Title = "Edit Category";
}

<main class="mt-4">
    <div class="container-fluid px-4">
        <div class="card">
            <div class="card-body row">
                <div class="col-md-12">
                    @using (Html.BeginForm("Edit", "CategoriesAdmin", new { id = Model.CategoryID }, FormMethod.Post, new { @class = "row g-3" }))
                    {
                        @Html.HiddenFor(model => model.CategoryID)

                        <fieldset>
                            <h2>EDIT CATEGORY</h2>

                            <!-- Category Name -->
                            <div class="col-lg-10 col-md-12">
                                @Html.LabelFor(model => model.CategoryName, "Category Name")
                                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", placeholder = "Category Name" } })
                                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                            </div>

                        </fieldset>

                        <div class="col-12 mt-3">
                            <button type="submit" class="btn btn-danger">Save Changes</button>
                            @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</main>

Areas/Admin/Views/CategoriesAdmin/Index.cshtml
@model List<HaVanThy_DoAn_WebDoTheThaoNike.Models.Category>

@{
    ViewBag.Title = "Index";
}

<style>
    .product-image {
        width: 30px;
        height: 30px;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }

    .edit-link {
        background-color: cadetblue;
        color: #fff;
        border: none;
    }

    .delete-link {
        background-color: #dc3545;
        color: #fff;
        border: none;
    }

    .btn-custom {
        padding: 5px 10px;
        margin: 2px;
    }

    .proName {
        text-decoration: none;
        font-weight: bold;
        color: black
    }
</style>

<main>
    <div class="container-fluid px-4">
        </br>
        <a href="@Url.Action("Create", "CategoriesAdmin", new { area = "Admin" })" class="btn btn-primary mb-1">Create New Category</a>

        <table class="table">
            <thead>
                <tr>
                    <th>Category ID</th>
                    <th>Category Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CategoryID</td>
                        <td>@item.CategoryName</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.CategoryID, controller = "CategoriesAdmin", area = "Admin" }, new { @class = "btn btn-custom btn-sm edit-link" }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.CategoryID, controller = "CategoriesAdmin", area = "Admin" }, new { @class = "btn btn-custom btn-sm delete-link" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</main>